# Generated by Django 5.0.7 on 2024-08-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('book_name', models.CharField(max_length=30)),
                ('book_cover', models.ImageField(upload_to='')),
                ('book_status', models.CharField(choices=[('RE', 'Rented'), ('AV', 'Available'), ('NAV', 'Not available')], default='AV', max_length=3)),
            ],
        ),
    ]
